# Generated by Django 2.1.7 on 2019-03-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190315_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='minimumcharge',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='minimumdays',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
